[build]
  command = "cd backend && npm install && npm run build && cd ../frontend && npm install && npm run build"
  publish = "frontend/dist"
  functions = "backend/dist"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/lambda/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
