services:
  - type: web
    name: samurai-kallpa-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    rootDir: backend
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3000
      - key: AWS_ACCESS_KEY_ID2
        sync: false
      - key: AWS_SECRET_ACCESS_KEY2
        sync: false
      - key: AWS_REGION2
        value: us-east-2
      - key: AWS_S3_BUCKET_NAME2
        sync: false
